= İlk Uygulamamız : ''Merhaba Dünya Uygulaması“

.Editable.c++
[source,c++]
----

#include<iostream>  <1>

int main() <2>

{  <3>

std::cout<<"hello world"<<endl;  <4>

return 0;  <5>

}  <6>
----
 
*1.* Burası direk olarak ön işlemci olarak bilinir.Derleyiciye bir dosya yerleştirme talimati verir.Bu dosya iostream kütüphanesi için gerekli kodları içerir.Bu kütüphane input,output kullanmaya izin veren kodları içerir.

*2.* Her C programının main () olarak bilinen bir metodu olmalıdır. Programın bilgisayarınızda yürütülmesine başladığınızda uygulamanın giriş noktası olarak adlandırılır. 
int kısmı, yöntemin dönüş türüdür. Yöntem adından sonraki parantezler (), bunun bir yöntemin olduğunu ve argüman almadığını, başka bir deyişle, değerleri aktarmak için parametre olmadığını belirtir.


*3.* C ++ 'daki metod gövdeleri açık bir küme ayracı ile başlar.

*4.* std::cout << "Hello World!";   Bu kod, Merhaba Dünya! Metnini göndermek için cout ('see out' olarak telaffuz edilir) olarak bilinen bir yöntem kullanır çıkış olarak konsola görüntüleme için kullanılır. 
Bu komutun std :: öneki, cout'un std olarak bilinen bir ad alanının parçası olduğunu göstermenin bir yoludur.
::, cout öğesinin std ad alanının bir parçası olduğunu belirtmek için kullanılır.
Ayrıca satırın noktalı virgülle bittiğine dikkat edin. C ++ ifadeleri (statements) noktalı virgüllerle sonlandırılır.


*5.*  Return ifadesi, bir arayana geri değer gönderilmesi beklendiğinde bir işlevi veya yöntemi sonlandırmak için kullanılır. 
 Bu durumda, arayan kişi işletim sistemidir ve döndürülen değer 0 tamsayıdır. 
 Program bu ifadeye ulaşırsa, 0 değerinin döndürülmesi, işletim sistemine kodun başarıyla çalıştırıldığının bir göstergesidir.
 Geçmişte, programcılar başarılı bir uygulama olduğunu belirtmek için 0 değerini ve programda bir yerde bir hata olduğunu göstermek için sıfır olmayan değerleri gösterirdi.

*6.* 
Bu çizgi main () fonksiyonunun gövdesini kapatır ve zorunludur, böylece derleyici, işlevin veya yöntemin nerede bittiğini bilir, fakat aynı zamanda dersin ilerleyen bölümlerinde değişken kapsam ve görünürlükle ele alınacak başka amaçlar için de kullanılır.





