= C++  Programlama Dili Genel Yapısı

C++ programla dili aynı C dili gibi iki temel bölümden oluşur.

* Ön işlemci direktifleri

* Ana fonksiyon ve yardımcı fonksiyonlar

=== Önişlemci Direktifleri

* #include<kütüphane_ismi . header_dosyası>: Bu komut önişlemciye hangi kütüphanenin header_dosyasını kullanarak programı çalıştırması gerekiğini söyler. Mesela C programlama dilince (#include<stdio.h>) diye tanımladığımız kod c++ dilinde (#include<iostream>) şeklinde tanımlarız ve kodlarımız bu kütüphanedeki kurallara uygun olarak derlenir ve bilgisayar tarafından çalıştırılır.

* #define tanım kalıp :  Bu komut önişlemciye  tanım isminde kalıp verisini yaz der ve ister ana fonksiyonda ister diğer fonksiyonlarda artık tanım ismini çağırdığımızda kalıp verisi gelecektir. Örnek olarak göstermek gerekirse;

 #define PI 3,14158263355333

Bu komutu kullanarak artık programımızın istediğimiz  yerinde bu PI değişkenini kullanabilirve işlem yapabiliriz.

=== Ana Fonksiyon Ve Yardımcı Fonksiyonlar

main() : Bu fonksiyon C programlama dersinde olduğu gibi C++ programlama dili için de ana fonksiyondur ve diğer fonksiyonların çalışması için gereklidir.

=== Yaım Biçimi

C++ büyük-küçük harfe duyarlı bir dildir. Örneğin karakter tipinin değişkeni char’dırr. Eğer bunun yerine Char veya CHAR yazarsanız derleyici bunu anlayamaz. 

Harf duyarlılığının yanında C++ dili aşağıdak özelliklere de sahiptir:

* derleyicinin kaynak kodu derlemeden önce çalıştırılacak görevleri belirten önişlemci yönergeleri

* namespace’leri dahil etmek için kullanılan using yönergeleri

* dönüş tipi, isim ve parametrelerden oluşan fonksiyon başlığı

* fonksiyonun yaptığı işlemlerin bulunduğu fonksiyon gövdesi 

*  C++ kaynak kodu dosyasındaki ifadeler

*  kodu anlaşılabilir kılmak için yorum satırları

*  fonksiyon çağırıcıya geri değer döndüren return ifadeleri
 
 * ifade gövdeleri için kullanılan süslü parantezler

C++ dili okunabilirliği kolaylaştırmak için whitespace kullanımına izin verir. Bir kaç istisna dışında derleyici whitespace karakterleri görmezden gelir.


=== C++ İfadeleri

Bir C++ programı fonksiyon, metot, sınıf gibi çeşitli bileşenlerden oluşur. Burada bulunan ifadeleri C++ kodunuzda kullanacsınız:

  * Tanımlamalar – Bunlar uygulamanızda kullanmak üzere değişken ve sabit tanımlamanızı sağlar.
    
  *  Atamalar – Bunlar değişkenlerinize değer atamanızı sağlar.
    
  * Önişlemci Yönergeleri
    
   * Yorum Satırları – Kodunuzun içerisinde dökümanlama yapmak için kullanılır.
    
  *  Fonksiyon Tanımlamaları




